name: azure-gpt-rag
metadata:
  template: azure-gpt-rag-orchestrator
infra:
  provider: bicep
  path: infra
  module: main
hooks:
  preprovision:
    posix:
      run: hooks/preProvision.sh
      interactive: true
    windows:
      run: hooks/preProvision.ps1
      interactive: true      
services:
  orchestrator:
    host: containerapp
    image: ${AZURE_CONTAINER_REGISTRY_NAME}.azurecr.io/azure-gpt-rag/orchestrator-build:${TAG}
                        