"""Runtime-neutral typed contracts for the orchestration core.

These dataclasses define the boundary between any transport layer
(FastAPI, hosted agents, CLI, or test harnesses) and the orchestration
core.  They carry no FastAPI or HTTP-specific imports so that any runtime
can construct and consume them without depending on the web framework.

Usage (FastAPI adapter)::

    turn = TurnRequest(
        ask=body.ask,
        conversation_id=body.conversation_id,
        question_id=body.question_id,
        user_context=user_context,
        request_access_token=access_token,
        correlation_id=correlation_id,
    )
    orchestrator = await Orchestrator.from_turn_request(turn)
    async for chunk in orchestrator.stream_turn(turn):
        yield chunk

Usage (hosted-agent runtime)::

    turn = TurnRequest(ask=invocation.text, user_context=invocation.identity)
    orchestrator = await Orchestrator.from_turn_request(turn)
    async for chunk in orchestrator.stream_turn(turn):
        await sink.write(chunk)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Optional


@dataclass
class TurnRequest:
    """Typed input contract for a single orchestration turn.

    All fields that the orchestration core needs to execute one conversational
    turn are gathered here so the contract can be expressed, validated, and
    tested independently of any specific transport mechanism.

    Attributes:
        ask: The user message / question to answer.
        conversation_id: Existing conversation to resume, or ``None`` to start
            a new one (the orchestrator will generate an id in that case).
        question_id: Optional caller-supplied id for the question within the
            conversation — used for feedback linkage and traceability.
        user_context: Arbitrary key/value context about the user (principal_id,
            principal_name, …).  Must not contain credentials or tokens.
        request_access_token: Short-lived bearer token forwarded from the
            caller so OBO-capable strategies can obtain downstream tokens.
            Kept in memory only — never persisted.
        correlation_id: Trace/correlation id propagated from the transport
            layer.  Generated by the orchestrator when ``None``.
    """

    ask: str
    conversation_id: Optional[str] = None
    question_id: Optional[str] = None
    user_context: Dict[str, Any] = field(default_factory=dict)
    request_access_token: Optional[str] = None
    correlation_id: Optional[str] = None
